esphome:
  name: esphome-office-single
  friendly_name: esphome-office-single

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[your key here]"

ota:
  - platform: esphome
    password: "[your password here]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Office-Single"
    password: "[password]"

captive_portal:
    
# Configure for single channel + Toggle Button
output:
  - platform: libretiny_pwm
    id: output_white
    pin: GPIO08

globals:
  - id: action_state
    type: int
    restore_value: no
    initial_value: '0'

binary_sensor:
  - platform: gpio
    pin:   GPIO14
    name: "Power Button"
    filters:
      - invert:
      - delayed_on_off: 20ms
    on_press:
      light.toggle:  lightstrip1
      
light:
  - platform: monochromatic
    output: output_white
    name: "White LED Strip"
    id: lightstrip1

    # Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_OFF
